### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Cucuzacu** [OpenCraft-Studios/Java-Edition#5]
I am sorry for bothering you, but can you please give me the release? I am not very good at compiling programs...

**Comment by CiroZDP** [comment]
Oh, the project is discontinued, but i'll do it for you

**Comment by CiroZDP** [comment]
Sorry, but this project is discontinued, you can check the ClassiCube repo in my account. Thank you!

**Comment by Cucuzacu** [comment]
I saw there is also a lwjgl edition. I managed to compile it as a jarfile with maven, but i cant execute it. What should i do??

**Comment by CiroZDP** [comment]
Sorry for replying late, but the LWJGL-Edition is work in progress. I'm trying to make a perfect copy of Minecraft, so this could take years of development

**Comment by CiroZDP** [comment]
Btw, i dont usually check messages here. if you have discord you can add me: cirodalto
